### ISSUE TITLE
Named Container

### ISSUE THREAD

**Issue by ayrbox** [Aabhusan/react_node_app_deployed-in-the-2-different-container#1]
Adding following configuration after this, will not require you ssh into container to proxy the ip.

https://github.com/Aabhusan/react_node_app_deployed-in-the-2-different-container/blob/master/react-app/nginx.conf#L36-L40 

``` 
location /hello {
    proxy_pass http://api:3000/hello;
}
```

**Comment by Aabhusan** [comment]
Yes, we can also use service name .
Thank you sir !!
